package com.loyltworks.mandelapremium.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class RegistrationRequest(
    val ActionType: String? = null,
    val DeviceId: String? = null,
    val CustomerId: String? = null
)

// ####################### Response  ########################

/*@JsonClass(generateAdapter = true)
data class RegistrationResponse(
    val GetCustomerDetailsMobileAppResult: GetCustomerDetailsMobileAppResult
)

@JsonClass(generateAdapter = true)
data class GetCustomerDetailsMobileAppResult(
    val ReturnMessage: Any? = null,
    val ReturnValue: Int? = null,
    val TotalRecords: Int? = null,
    val lstCustomerIdentityInfo: List<LstCustomerIdentityInfo>? = null,
    val lstCustomerJson: List<LstCustomerJson>? = null,
    val lstCustomerOfficalInfoJson: List<LstCustomerOfficalInfoJson>? = null,
    val lstVehicleJson: List<LstVehicleJson>? = null
)

@JsonClass(generateAdapter = true)
data class LstCustomerIdentityInfo(
    val IdentityDocument: String? = null,
    val IdentityID: Int? = null,
    val IdentityNo: String? = null,
    val IdentityType: String? = null,
    val IdentityTypeID: Int? = null,
    val IsNewIdentity: Boolean? = null
)

@JsonClass(generateAdapter = true)
data class LstCustomerJson(
    val AccountComStatus: Int? = null,
    var RegStatus: Int? = null,
    val AccountNumber: String? = null,
    val AccountStatus: String? = null,
    val AcountHolderName: String? = null,
    val Address1: String? = null,
    val Address2: String? = null,
    val AddressId: Int? = null,
    val AgeGroupId: Int? = null,
    val Anniversary: Any? = null,
    val BankAddress: String? = null,
    val BankBranch: String? = null,
    val BankCountryId: Int? = null,
    val BankCountry: String? = null,
    val BankCountryName: String? = null,
    val BankName: String? = null,
    val BicSwiftCode: String? = null,
    val BsbAbaRoutingNumber: String? = null,
    val ChassisNumber: String? = null,
    val CityId: Int? = null,
    val CityName: String? = null,
    val ContractId: Int? = null,
    val CountryId: Int? = null,
    val CountryName: String? = null,
    val ContractFileName: String? = null,
    val ContractName: String? = null,
    val CurrencyId: Int? = null,
    val Currency: String? = null,
    val CustFamilyId: Int? = null,
    val CustomerCategoryId: Int? = null,
    val CustomerDetailId: Int? = null,
    val CustomerId: Int? = null,
    val CustomerRelationshipId: Int? = null,
    val CustomerRemarks: Any? = null,
    val CustomerType: String? = null,
    val CustomerTypeID: Int? = null,
    val Customer_Grade_ID: Int? = null,
    val District: String? = null,
    val DistrictId: Int? = null,
    val DistrictName: Any? = null,
    val Email: String? = null,
    val EmailStatus: Int? = null,
    val EnrollmentReferenceNumber: String? = null,
    val ExecutiveName: Any? = null,
    val FamilyMemberBirthday: Any? = null,
    val FamilyMemberName: Any? = null,
    val FirstName: String? = null,
    val Gender: Any? = null,
    val IsActive: Int? = null,
    val IFSCCode: Any? = null,
    val IbanNumber: String? = null,
    val IdentificationNo: String? = null,
    val IdentificationOthers: Any? = null,
    val IncomeRangeId: Int? = null,
    val InsuranceRenewalAmount: Int? = null,
    val IsBlackListed: Boolean? = null,
    val IsGradeVerified: Boolean? = null,
    val IsSmartphoneUser: Boolean? = null,
    val IsVerified: Int? = null,
    val IsWhatsappUser: Boolean? = null,
    val JCreatedDate: String? = null,
    val JDOB: String? = null,
    val JD_InvoiceNo: Any? = null,
    val JEnrollmentReferenceDate: Any? = null,
    val JInsuranceExpDate: Any? = null,
    val JJD_InvoiceDate: Any? = null,
    val JPolicyDate: Any? = null,
    val LIdentificationType: Int? = null,
    val LaborAmount: Int? = null,
    val Landmark: String? = null,
    val LanguageId: Int? = null,
    val LanguageName: Any? = null,
    val LastName: String? = null,
    val Locality: String? = null,
    val LocationCode: String? = null,
    val LocationId: Int? = null,
    val LocationName: String? = null,
    val LoyaltyId: String? = null,
    val MaritalStatus: Any? = null,
    val MerchantId: Int? = null,
    val Mobile: String? = null,
    val MobileNumberLimitation: Int? = null,
    val MobilePrefix: String? = null,
    val Mobile_Two: String? = null,
    val ModelNumber: String? = null,
    val NativeCountryId: Int? = null,
    val NativeStateId: Int? = null,
    val NativeStateName: String? = null,
    val Nominee: Any? = null,
    val NomineeDOB: Any? = null,
    val PolicyNumber: String? = null,
    val ProfessionId: Int? = null,
    val ProfilePicture: Any? = null,
    val ReferedBy: Any? = null,
    val RegType: String? = null,
    val Relationship: Any? = null,
    val ReligionID: Int? = null,
    val Remarks: String? = null,
    val StateId: Int? = null,
    val StateName: Any? = null,
    val TalukId: Int? = null,
    val TalukName: Any? = null,
    val TehsilBlockMandal: String? = null,
    val Title: String? = null,
    val UserId: Int? = null,
    val VehicleBrand: Any? = null,
    val VehicleID: Int? = null,
    val VehicleNumber: String? = null,
    val Village: String? = null,
    val WalletNumber: Any? = null,
    val WhatsAppNumber: Any? = null,
    val Zip: String? = null,
    val bankAccountVerifiedStatus: Boolean? = null
)

@JsonClass(generateAdapter = true)
data class LstCustomerOfficalInfoJson(
    val CompanyName: String? = null,
    val DepartmentIdOfficial: Int? = null,
    val Designation: Any? = null,
    val DesignationIdOfficial: Int? = null,
    val FirmMobile: Any? = null,
    val FirmSize: Any? = null,
    val FirmTypeID: Int? = null,
    val GSTNumber: Any? = null,
    val IncorporationDate: Any? = null,
    val JobTypeID: Int? = null,
    val OfficalEmail: Any? = null,
    val OwnerName: String? = null,
    val PhoneOffice: String? = null,
    val PhoneResidence: Any? = null,
    val SAPCode: Any? = null,
    val StdCode: Any? = null,
    val StoreName: Any? = null
)

@JsonClass(generateAdapter = true)
data class LstVehicleJson (
    var JVehicleBrand: String? = null,
    var ModelNo: String? = null,
    var VehicleId: Int? = null,
    var VehicleNo: String? = null,
    var VinChasis: String? = null,
    var VehicleType: String? = null,
    var FuelType: String? = null
)*/

/*
@JsonClass(generateAdapter = true)
data class RegistrationResponse(
    var GetCustomerDetailsMobileAppResult: GetCustomerDetailsMobileAppResult? = null
)
@JsonClass(generateAdapter = true)
data class GetCustomerDetailsMobileAppResult(
    var ReturnMessage: Any? = null,
    var ReturnValue: Int? = null,
    var TotalRecords: Int? = null,
    var lstCustomerIdentityInfo: Any? = null,
    var lstCustomerJson: List<LstCustomerJson?>? = null,
    var lstCustomerOfficalInfoJson: List<LstCustomerOfficalInfoJson?>? = null,
    var lstVehicleJson: List<LstVehicleJson?>? = null
)
@JsonClass(generateAdapter = true)
data class LstCustomerJson(
    var AccountComStatus: Int? = null,
    var AccountNumber: Any? = null,
    var AccountStatus: String? = null,
    var AccountType: Any? = null,
    var AccountTypeID: Int? = null,
    var AcountHolderName: Any? = null,
    var Address1: String? = null,
    var Address2: String? = null,
    var AddressId: Int? = null,
    var AddressLatitude: Any? = null,
    var AddressLongitude: Any? = null,
    var AgeGroupId: Int? = null,
    var Anniversary: Any? = null,
    var BankAddress: Any? = null,
    var BankBranch: Any? = null,
    var BankCountryId: Int? = null,
    var BankCountryName: Any? = null,
    var BankName: Any? = null,
    var BicSwiftCode: Any? = null,
    var BsbAbaRoutingNumber: Any? = null,
    var ChassisNumber: String? = null,
    var CityId: Int? = null,
    var CityName: String? = null,
    var ContractFileName: Any? = null,
    var ContractId: Int? = null,
    var ContractName: Any? = null,
    var CountryId: Int? = null,
    var CountryName: String? = null,
    var Currency: Any? = null,
    var CurrencyId: Int? = null,
    var CustFamilyId: Int? = null,
    var CustomerCategoryId: Int? = null,
    var CustomerDetailId: Int? = null,
    var CustomerGrade: String? = null,
    var CustomerId: Int? = null,
    var CustomerRelationshipId: Int? = null,
    var CustomerRemarks: Any? = null,
    var CustomerType: String? = null,
    var CustomerTypeID: Int? = null,
    var CustomerTypeId: Int? = null,
    var Customer_Grade_ID: Int? = null,
    var DOB: Any? = null,
    var District: String? = null,
    var DistrictId: Int? = null,
    var DistrictName: Any? = null,
    var Email: String? = null,
    var EmailStatus: Int? = null,
    var EngineNumber: Any? = null,
    var EnrollmentReferenceNumber: String? = null,
    var ExecutiveName: String? = null,
    var FamilyMemberBirthday: Any? = null,
    var FamilyMemberName: String? = null,
    var FirstName: String? = null,
    var Gender: String? = null,
    var IFSCCode: Any? = null,
    var IbanNumber: Any? = null,
    var IdentificationNo: String? = null,
    var IdentificationOthers: Any? = null,
    var IncomeRangeId: Int? = null,
    var InsuranceRenewalAmount: Int? = null,
    var InvoiceAmount: Any? = null,
    var InvoiceNo: Any? = null,
    var IsActive: Int? = null,
    var IsBlackListed: Boolean? = null,
    var IsGradeVerified: Boolean? = null,
    var IsSmartphoneUser: Boolean? = null,
    var IsUpdatePassword: Boolean? = null,
    var IsVerified: Int? = null,
    var IsVinChassis_Active: Any? = null,
    var IsWhatsappUser: Boolean? = null,
    var JCreatedDate: String? = null,
    var JDOB: String? = null,
    var JD_InvoiceNo: String? = null,
    var JDateOfSale: Any? = null,
    var JEnrollmentReferenceDate: Any? = null,
    var JInsuranceExpDate: Any? = null,
    var JJD_InvoiceDate: String? = null,
    var JPolicyDate: Any? = null,
    var LIdentificationType: Int? = null,
    var LaborAmount: Int? = null,
    var Landmark: String? = null,
    var LanguageId: Int? = null,
    var LanguageName: Any? = null,
    var LastName: String? = null,
    var Locality: String? = null,
    var LocationCode: String? = null,
    var LocationId: Int? = null,
    var LocationName: String? = null,
    var LoyaltyId: String? = null,
    var MaritalStatus: Any? = null,
    var MerchantId: Int? = null,
    var Mobile: String? = null,
    var MobileNumberLimitation: Int? = null,
    var MobilePrefix: String? = null,
    var Mobile_Two: String? = null,
    var ModelNumber: String? = null,
    var NativeCountryId: Int? = null,
    var NativeStateId: Int? = null,
    var NativeStateName: String? = null,
    var Nominee: Any? = null,
    var NomineeDOB: Any? = null,
    var Password: Any? = null,
    var PlainPassword: Any? = null,
    var PolicyNumber: String? = null,
    var ProfessionId: Int? = null,
    var ProfilePicture: String? = null,
    var RELATED_PROJECT_TYPE: Any? = null,
    var ReferedBy: Any? = null,
    var RegStatus: Int? = null,
    var RegType: String? = null,
    var Relationship: String? = null,
    var ReligionID: Int? = null,
    var Remarks: Any? = null,
    var StateId: Int? = null,
    var StateName: Any? = null,
    var TalukId: Int? = null,
    var TalukName: Any? = null,
    var TehsilBlockMandal: String? = null,
    var Title: String? = null,
    var TradeLicence: Any? = null,
    var UserId: Int? = null,
    var VehicleBrand: String? = null,
    var VehicleID: Int? = null,
    var VehicleNumber: String? = null,
    var VehicleType: Any? = null,
    var Village: String? = null,
    var WalletNumber: Any? = null,
    var WhatsAppNumber: Any? = null,
    var Zip: String? = null,
    var bankAccountVerifiedStatus: Int? = null
)
@JsonClass(generateAdapter = true)
data class LstCustomerOfficalInfoJson(
    var CityId: Int? = null,
    var CityName: Any? = null,
    var CompanyName: String? = null,
    var CountryId: Int? = null,
    var CountryName: Any? = null,
    var DepartmentIdOfficial: Int? = null,
    var Designation: Any? = null,
    var DesignationIdOfficial: Int? = null,
    var FirmAddress: String? = null,
    var FirmMobile: Any? = null,
    var FirmSize: Any? = null,
    var FirmTypeID: Int? = null,
    var FirmTypeName: String? = null,
    var GSTNumber: Any? = null,
    var IncorporationDate: Any? = null,
    var IndustryID: Int? = null,
    var JobTypeID: Int? = null,
    var JobTypeName: Any? = null,
    var OfficalEmail: Any? = null,
    var OwnerName: Any? = null,
    var PhoneOffice: String? = null,
    var PhoneResidence: String? = null,
    var SAPCode: Any? = null,
    var StateId: Int? = null,
    var StateName: Any? = null,
    var StdCode: Any? = null,
    var StoreName: Any? = null,
    var TargetCreditPeriod: Int? = null,
    var TargetValue: Int? = null,
    var VenderCode: Any? = null,
    var Zip: Any? = null
)
@JsonClass(generateAdapter = true)
data class LstVehicleJson(
    var AverageRunningPerMonth: String? = null,
    var DrivenBy: String? = null,
    var EngineNumber: String? = null,
    var FuelType: String? = null,
    var FuelTypeID: Int? = null,
    var InsuranceCompany: String? = null,
    var InsuranceExpiryDate: String? = null,
    var InsuranceRenewalNumber: String? = null,
    var InvoiceDate: String? = null,
    var InvoiceNumber: String? = null,
    var IsDriverChanging: String? = null,
    var IsVehicleActive: Boolean? = null,
    var IsVinNumberActive: Boolean? = null,
    var JVehicleBrand: String? = null,
    var LaborAmount: String? = null,
    var ModelName: String? = null,
    var ModelNo: String? = null,
    var Payload: String? = null,
    var PolicyDate: String? = null,
    var PolicyNumber: String? = null,
    var PresentKM: String? = null,
    var ServiceDueDate: String? = null,
    var VehicleId: Int? = null,
    var VehicleModelNumber: String? = null,
    var VehicleNo: String? = null,
    var VehicleType: String? = null,
    var VinChasis: String? = null
)
*/


@JsonClass(generateAdapter = true)
data class RegistrationResponse(
    @Json(name = "GetCustomerDetailsMobileAppResult")
    var getCustomerDetailsMobileAppResult: GetCustomerDetailsMobileAppResult? = null
)

@JsonClass(generateAdapter = true)
data class GetCustomerDetailsMobileAppResult(
    @Json(name = "CustomerBasicInfoList")
    var customerBasicInfoList: Any? = null,
    @Json(name = "CustomerFamilyList")
    var customerFamilyList: Any? = null,
    @Json(name = "CustomerPreferenceList")
    var customerPreferenceList: Any? = null,
    @Json(name = "HierarchyMapDetails")
    var hierarchyMapDetails: Any? = null,
    @Json(name = "lstCustomerIdentityInfo")
    var lstCustomerIdentityInfo: Any? = null,
    @Json(name = "lstCustomerJson")
    var lstCustomerJson: List<LstCustomerJson?>? = null,
    @Json(name = "lstCustomerOfficalInfoJson")
    var lstCustomerOfficalInfoJson: List<LstCustomerOfficalInfoJson?>? = null,
    @Json(name = "lstVehicleJson")
    var lstVehicleJson: List<LstVehicleJson?>? = null,
    @Json(name = "LstWorkSiteInfoDetails")
    var lstWorkSiteInfoDetails: Any? = null,
    @Json(name = "MappedProductList")
    var mappedProductList: Any? = null,
    @Json(name = "ObjCustomer")
    var objCustomer: Any? = null,
    @Json(name = "ObjCustomerDetails")
    var objCustomerDetails: Any? = null,
    @Json(name = "ObjCustomerOfficalInfo")
    var objCustomerOfficalInfo: Any? = null,
    @Json(name = "PDF")
    var pDF: Any? = null,
    @Json(name = "ReturnMessage")
    var returnMessage: Any? = null,
    @Json(name = "ReturnValue")
    var returnValue: Int? = null,
    @Json(name = "SubscriptionDetails")
    var subscriptionDetails: Any? = null,
    @Json(name = "TotalRecords")
    var totalRecords: Int? = null
)

@JsonClass(generateAdapter = true)
data class LstCustomerJson(
    @Json(name = "AadharNumber")
    var aadharNumber: Any? = null,
    @Json(name = "AccountComStatus")
    var accountComStatus: Int? = null,
    @Json(name = "AccountNumber")
    var accountNumber: Any? = null,
    @Json(name = "AccountStatus")
    var accountStatus: String? = null,
    @Json(name = "AccountType")
    var accountType: Any? = null,
    @Json(name = "AccountTypeID")
    var accountTypeID: Int? = null,
    @Json(name = "AcountHolderName")
    var acountHolderName: Any? = null,
    @Json(name = "Address1")
    var address1: String? = null,
    @Json(name = "Address2")
    var address2: String? = null,
    @Json(name = "AddressId")
    var addressId: Int? = null,
    @Json(name = "AddressLatitude")
    var addressLatitude: Any? = null,
    @Json(name = "AddressLongitude")
    var addressLongitude: Any? = null,
    @Json(name = "AgeGroupId")
    var ageGroupId: Int? = null,
    @Json(name = "Anniversary")
    var anniversary: Any? = null,
    @Json(name = "AreaId")
    var areaId: Int? = null,
    @Json(name = "AreaName")
    var areaName: Any? = null,
    @Json(name = "AutoAccountType")
    var autoAccountType: Any? = null,
    @Json(name = "AutoBankCounty")
    var autoBankCounty: Any? = null,
    @Json(name = "AutoBankPostCode")
    var autoBankPostCode: Any? = null,
    @Json(name = "bankAccountVerifiedStatus")
    var bankAccountVerifiedStatus: Int? = null,
    @Json(name = "BankAddress")
    var bankAddress: Any? = null,
    @Json(name = "BankBranch")
    var bankBranch: Any? = null,
    @Json(name = "BankCity")
    var bankCity: Any? = null,
    @Json(name = "BankCode")
    var bankCode: Any? = null,
    @Json(name = "BankCountryId")
    var bankCountryId: Int? = null,
    @Json(name = "BankCountryName")
    var bankCountryName: Any? = null,
    @Json(name = "BankName")
    var bankName: Any? = null,
    @Json(name = "BankPassbookImage")
    var bankPassbookImage: Any? = null,
    @Json(name = "BankTransferMode")
    var bankTransferMode: Int? = null,
    @Json(name = "BicSwiftCode")
    var bicSwiftCode: Any? = null,
    @Json(name = "BranchCode")
    var branchCode: Any? = null,
    @Json(name = "BsbAbaRoutingNumber")
    var bsbAbaRoutingNumber: Any? = null,
    @Json(name = "ChassisNumber")
    var chassisNumber: String? = null,
    @Json(name = "CityId")
    var cityId: Int? = null,
    @Json(name = "CityName")
    var cityName: String? = null,
    @Json(name = "Company")
    var company: Any? = null,
    @Json(name = "ContractFileName")
    var contractFileName: Any? = null,
    @Json(name = "ContractId")
    var contractId: Int? = null,
    @Json(name = "ContractName")
    var contractName: Any? = null,
    @Json(name = "CountryId")
    var countryId: Int? = null,
    @Json(name = "CountryName")
    var countryName: String? = null,
    @Json(name = "CreatedBy")
    var createdBy: Any? = null,
    @Json(name = "CreatedDate")
    var createdDate: Any? = null,
    @Json(name = "Currency")
    var currency: Any? = null,
    @Json(name = "CurrencyId")
    var currencyId: Int? = null,
    @Json(name = "CustFamilyId")
    var custFamilyId: Int? = null,
    @Json(name = "CustomerCategory")
    var customerCategory: Any? = null,
    @Json(name = "CustomerCategoryId")
    var customerCategoryId: Int? = null,
    @Json(name = "CustomerDetailId")
    var customerDetailId: Int? = null,
    @Json(name = "CustomerGrade")
    var customerGrade: String? = null,
    @Json(name = "Customer_Grade_ID")
    var customerGradeID: Int? = null,
    @Json(name = "CustomerId")
    var customerId: Int? = null,
    @Json(name = "CustomerOrderCount")
    var customerOrderCount: Int? = null,
    @Json(name = "CustomerRelationshipId")
    var customerRelationshipId: Int? = null,
    @Json(name = "CustomerRemarks")
    var customerRemarks: Any? = null,
    @Json(name = "CustomerType")
    var customerType: String? = null,
    @Json(name = "CustomerTypeID")
    var customerTypeID: Int? = null,
    @Json(name = "CustomerTypeId")
    var customerTypeId: Int? = null,
    @Json(name = "DOB")
    var dOB: Any? = null,
    @Json(name = "DealerName")
    var dealerName: Any? = null,
    @Json(name = "DealerUserId")
    var dealerUserId: Any? = null,
    @Json(name = "DepartmentId")
    var departmentId: Int? = null,
    @Json(name = "DesignationId")
    var designationId: Int? = null,
    @Json(name = "DisplayImage")
    var displayImage: Any? = null,
    @Json(name = "District")
    var district: String? = null,
    @Json(name = "DistrictId")
    var districtId: Int? = null,
    @Json(name = "DistrictName")
    var districtName: Any? = null,
    @Json(name = "Domain")
    var domain: Any? = null,
    @Json(name = "Email")
    var email: String? = null,
    @Json(name = "EmailStatus")
    var emailStatus: Int? = null,
    @Json(name = "EngineNumber")
    var engineNumber: Any? = null,
    @Json(name = "EnrollmentReferenceDate")
    var enrollmentReferenceDate: Any? = null,
    @Json(name = "EnrollmentReferenceNumber")
    var enrollmentReferenceNumber: String? = null,
    @Json(name = "EnrollmentStatus")
    var enrollmentStatus: Boolean? = null,
    @Json(name = "ExecutiveName")
    var executiveName: String? = null,
    @Json(name = "FamilyMemberBirthday")
    var familyMemberBirthday: Any? = null,
    @Json(name = "FamilyMemberName")
    var familyMemberName: String? = null,
    @Json(name = "FirstName")
    var firstName: String? = null,
    @Json(name = "Gender")
    var gender: String? = null,
    @Json(name = "IFSCCode")
    var iFSCCode: Any? = null,
    @Json(name = "IbanNumber")
    var ibanNumber: Any? = null,
    @Json(name = "IdentificationNo")
    var identificationNo: String? = null,
    @Json(name = "IdentificationOthers")
    var identificationOthers: Any? = null,
    @Json(name = "IncomeRangeId")
    var incomeRangeId: Int? = null,
    @Json(name = "InsuranceExpDate")
    var insuranceExpDate: Any? = null,
    @Json(name = "InsuranceRenewalAmount")
    var insuranceRenewalAmount: Int? = null,
    @Json(name = "InvoiceAmount")
    var invoiceAmount: Any? = null,
    @Json(name = "InvoiceNo")
    var invoiceNo: Any? = null,
    @Json(name = "IsActive")
    var isActive: Int? = null,
    @Json(name = "IsBankPassbookNewImage")
    var isBankPassbookNewImage: Boolean? = null,
    @Json(name = "IsBlackListed")
    var isBlackListed: Boolean? = null,
    @Json(name = "IsGradeVerified")
    var isGradeVerified: Boolean? = null,
    @Json(name = "IsSmartphoneUser")
    var isSmartphoneUser: Boolean? = null,
    @Json(name = "IsUpdatePassword")
    var isUpdatePassword: Boolean? = null,
    @Json(name = "IsVerified")
    var isVerified: Int? = null,
    @Json(name = "IsVinChassis_Active")
    var isVinChassisActive: Any? = null,
    @Json(name = "IsWhatsappUser")
    var isWhatsappUser: Boolean? = null,
    @Json(name = "JAnniversary")
    var jAnniversary: Any? = null,
    @Json(name = "JCreatedDate")
    var jCreatedDate: String? = null,
    @Json(name = "JD_InvoiceDate")
    var jDInvoiceDate: Any? = null,
    @Json(name = "JD_InvoiceNo")
    var jDInvoiceNo: String? = null,
    @Json(name = "JDOB")
    var jDOB: String? = null,
    @Json(name = "JDateOfSale")
    var jDateOfSale: Any? = null,
    @Json(name = "JEnrollmentReferenceDate")
    var jEnrollmentReferenceDate: Any? = null,
    @Json(name = "JInsuranceExpDate")
    var jInsuranceExpDate: Any? = null,
    @Json(name = "JJD_InvoiceDate")
    var jJDInvoiceDate: String? = null,
    @Json(name = "JPolicyDate")
    var jPolicyDate: Any? = null,
    @Json(name = "LIdentificationType")
    var lIdentificationType: Int? = null,
    @Json(name = "LaborAmount")
    var laborAmount: Int? = null,
    @Json(name = "Landmark")
    var landmark: String? = null,
    @Json(name = "LanguageId")
    var languageId: Int? = null,
    @Json(name = "LanguageName")
    var languageName: String? = null,
    @Json(name = "LastName")
    var lastName: String? = null,
    @Json(name = "Locality")
    var locality: String? = null,
    @Json(name = "LocationCode")
    var locationCode: String? = null,
    @Json(name = "LocationId")
    var locationId: Int? = null,
    @Json(name = "LocationName")
    var locationName: String? = null,
    @Json(name = "LoyaltyId")
    var loyaltyId: String? = null,
    @Json(name = "LoyaltyIdAutoGen")
    var loyaltyIdAutoGen: Boolean? = null,
    @Json(name = "MaritalStatus")
    var maritalStatus: String? = null,
    @Json(name = "MemberSince")
    var memberSince: Any? = null,
    @Json(name = "MerchantId")
    var merchantId: Int? = null,
    @Json(name = "Mobile")
    var mobile: String? = null,
    @Json(name = "MobileNumberLimitation")
    var mobileNumberLimitation: Int? = null,
    @Json(name = "MobilePrefix")
    var mobilePrefix: String? = null,
    @Json(name = "Mobile_Two")
    var mobileTwo: String? = null,
    @Json(name = "ModelNumber")
    var modelNumber: String? = null,
    @Json(name = "NativeCountryId")
    var nativeCountryId: Int? = null,
    @Json(name = "NativeStateId")
    var nativeStateId: Int? = null,
    @Json(name = "NativeStateName")
    var nativeStateName: String? = null,
    @Json(name = "Nominee")
    var nominee: Any? = null,
    @Json(name = "NomineeDOB")
    var nomineeDOB: Any? = null,
    @Json(name = "ParentCustomerId")
    var parentCustomerId: Int? = null,
    @Json(name = "Password")
    var password: Any? = null,
    @Json(name = "PayOut")
    var payOut: Int? = null,
    @Json(name = "PlainPassword")
    var plainPassword: Any? = null,
    @Json(name = "PointBalance")
    var pointBalance: Int? = null,
    @Json(name = "PolicyDate")
    var policyDate: Any? = null,
    @Json(name = "PolicyNumber")
    var policyNumber: String? = null,
    @Json(name = "ProfessionId")
    var professionId: Int? = null,
    @Json(name = "ProfilePicture")
    var profilePicture: String? = null,
    @Json(name = "RELATED_PROJECT_TYPE")
    var rELATEDPROJECTTYPE: Any? = null,
    @Json(name = "RecipientPhonenumber")
    var recipientPhonenumber: Any? = null,
    @Json(name = "RecipientType")
    var recipientType: Any? = null,
    @Json(name = "ReferedBy")
    var referedBy: Any? = null,
    @Json(name = "ReferralCode")
    var referralCode: Any? = null,
    @Json(name = "ReferrerCode")
    var referrerCode: Any? = null,
    @Json(name = "RegStatus")
    var regStatus: Int? = null,
    @Json(name = "RegType")
    var regType: String? = null,
    @Json(name = "RegistrationSource")
    var registrationSource: Int? = null,
    @Json(name = "Relationship")
    var relationship: String? = null,
    @Json(name = "ReligionID")
    var religionID: Int? = null,
    @Json(name = "Remarks")
    var remarks: Any? = null,
    @Json(name = "SSID")
    var sSID: Any? = null,
    @Json(name = "StateId")
    var stateId: Int? = null,
    @Json(name = "StateName")
    var stateName: Any? = null,
    @Json(name = "TalukId")
    var talukId: Int? = null,
    @Json(name = "TalukName")
    var talukName: Any? = null,
    @Json(name = "TaxId")
    var taxId: Any? = null,
    @Json(name = "TehsilBlockMandal")
    var tehsilBlockMandal: String? = null,
    @Json(name = "Title")
    var title: String? = null,
    @Json(name = "TradeLicence")
    var tradeLicence: Any? = null,
    @Json(name = "UPI_ID")
    var uPIID: Any? = null,
    @Json(name = "User")
    var user: Any? = null,
    @Json(name = "UserId")
    var userId: Int? = null,
    @Json(name = "VehicleBrand")
    var vehicleBrand: String? = null,
    @Json(name = "VehicleID")
    var vehicleID: Int? = null,
    @Json(name = "VehicleNumber")
    var vehicleNumber: String? = null,
    @Json(name = "VehicleType")
    var vehicleType: Any? = null,
    @Json(name = "VerifiedStatus")
    var verifiedStatus: Any? = null,
    @Json(name = "Village")
    var village: String? = null,
    @Json(name = "WalletNumber")
    var walletNumber: Any? = null,
    @Json(name = "WalletVerifiedStatus")
    var walletVerifiedStatus: Boolean? = null,
    @Json(name = "WhatsAppNumber")
    var whatsAppNumber: Any? = null,
    @Json(name = "Zip")
    var zip: String? = null
)

@JsonClass(generateAdapter = true)
data class LstCustomerOfficalInfoJson(
    @Json(name = "Address")
    var address: Any? = null,
    @Json(name = "BankTransferMode")
    var bankTransferMode: Any? = null,
    @Json(name = "CityId")
    var cityId: Int? = null,
    @Json(name = "CityName")
    var cityName: Any? = null,
    @Json(name = "CompanyName")
    var companyName: String? = null,
    @Json(name = "CountryId")
    var countryId: Int? = null,
    @Json(name = "CountryName")
    var countryName: Any? = null,
    @Json(name = "DepartmentIdOfficial")
    var departmentIdOfficial: Int? = null,
    @Json(name = "Designation")
    var designation: Any? = null,
    @Json(name = "DesignationIdOfficial")
    var designationIdOfficial: Int? = null,
    @Json(name = "DistrictId")
    var districtId: Int? = null,
    @Json(name = "EstablishDate")
    var establishDate: Any? = null,
    @Json(name = "FirmAddress")
    var firmAddress: String? = null,
    @Json(name = "FirmMobile")
    var firmMobile: Any? = null,
    @Json(name = "FirmSize")
    var firmSize: Any? = null,
    @Json(name = "FirmTypeID")
    var firmTypeID: Int? = null,
    @Json(name = "FirmTypeName")
    var firmTypeName: String? = null,
    @Json(name = "GSTDocument")
    var gSTDocument: Any? = null,
    @Json(name = "GSTNumber")
    var ggSTNumber: Any? = null,
    @Json(name = "IncorporationDate")
    var incorporationDate: Any? = null,
    @Json(name = "IndustryID")
    var industryID: Int? = null,
    @Json(name = "IsGSTNumber")
    var isGSTNumber: Any? = null,
    @Json(name = "JobTypeID")
    var jobTypeID: Int? = null,
    @Json(name = "JobTypeName")
    var jobTypeName: Any? = null,
    @Json(name = "OfficalEmail")
    var officalEmail: Any? = null,
    @Json(name = "OwnerName")
    var ownerName: Any? = null,
    @Json(name = "PhoneOffice")
    var phoneOffice: String? = null,
    @Json(name = "PhoneResidence")
    var phoneResidence: String? = null,
    @Json(name = "SAPCode")
    var sAPCode: Any? = null,
    @Json(name = "StateId")
    var stateId: Int? = null,
    @Json(name = "StateName")
    var stateName: Any? = null,
    @Json(name = "StdCode")
    var stdCode: Any? = null,
    @Json(name = "StoreName")
    var storeName: Any? = null,
    @Json(name = "TahasilImage")
    var tahasilImage: Any? = null,
    @Json(name = "TalukId")
    var talukId: Int? = null,
    @Json(name = "TargetCreditPeriod")
    var targetCreditPeriod: Int? = null,
    @Json(name = "TargetPoint")
    var targetPoint: Int? = null,
    @Json(name = "TargetValue")
    var targetValue: Int? = null,
    @Json(name = "VenderCode")
    var venderCode: Any? = null,
    @Json(name = "Zip")
    var zip: Any? = null
)

@JsonClass(generateAdapter = true)
data class LstVehicleJson(
    @Json(name = "AverageRunningPerMonth")
    var averageRunningPerMonth: String? = null,
    @Json(name = "DrivenBy")
    var drivenBy: String? = null,
    @Json(name = "EngineNumber")
    var engineNumber: String? = null,
    @Json(name = "FuelType")
    var fuelType: String? = null,
    @Json(name = "FuelTypeID")
    var fuelTypeID: Int? = null,
    @Json(name = "InsuranceCompany")
    var insuranceCompany: String? = null,
    @Json(name = "InsuranceExpiryDate")
    var insuranceExpiryDate: String? = null,
    @Json(name = "InsuranceRenewalNumber")
    var insuranceRenewalNumber: String? = null,
    @Json(name = "InvoiceDate")
    var invoiceDate: String? = null,
    @Json(name = "InvoiceNumber")
    var invoiceNumber: String? = null,
    @Json(name = "IsDriverChanging")
    var isDriverChanging: String? = null,
    @Json(name = "IsVehicleActive")
    var isVehicleActive: Boolean? = null,
    @Json(name = "IsVinNumberActive")
    var isVinNumberActive: Boolean? = null,
    @Json(name = "JVehicleBrand")
    var jVehicleBrand: String? = null,
    @Json(name = "LaborAmount")
    var laborAmount: String? = null,
    @Json(name = "ModelName")
    var modelName: String? = null,
    @Json(name = "ModelNo")
    var modelNo: String? = null,
    @Json(name = "Payload")
    var payload: String? = null,
    @Json(name = "PolicyDate")
    var policyDate: String? = null,
    @Json(name = "PolicyNumber")
    var policyNumber: String? = null,
    @Json(name = "PresentKM")
    var presentKM: String? = null,
    @Json(name = "ServiceDueDate")
    var serviceDueDate: String? = null,
    @Json(name = "VehicleId")
    var vehicleId: Int? = null,
    @Json(name = "VehicleModelNumber")
    var vehicleModelNumber: String? = null,
    @Json(name = "VehicleNo")
    var vehicleNo: String? = null,
    @Json(name = "VehicleType")
    var vehicleType: String? = null,
    @Json(name = "VinChasis")
    var vinChasis: String? = null
)